preload = ~/Pictures/Wallpapers/fedora-f43.png
# wallpaper = DP-2, ~/Pictures/Wallpapers/fedora-f43.png

wallpaper {
    monitor = DP-2
    path = ~/Pictures/Wallpapers/fedora-f43.png
    fit_mode = cover
}
